fix workflow

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -231,19 +231,19 @@ jobs:
           name: Deploy to AWS staging environment
           command: |
             set -x
-            ssh -o StrictHostKeyChecking=no $STAGING_SSH_USER@$STAGING_SSH_HOST \<< 'EOF'
+            ssh -o StrictHostKeyChecking=no $STAGING_SSH_USER@$STAGING_SSH_HOST \<< EOF
             
             # Docker login
-            docker login ghcr.io -u $GHCR_USERNAME --password $GHCR_PAT
+            echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
 
             # Pull the Docker image
             echo "Pulling image: $DOCKER_REPOSITORY:$CIRCLE_BRANCH"
-            docker pull $$DOCKER_REPOSITORY:$CIRCLE_BRANCH || exit 1
+            docker pull $DOCKER_REPOSITORY:$CIRCLE_BRANCH || exit 1
             
             # Stop and remove any existing container
             echo "Stopping existing container (if any)..."
-            docker stop $PREPRODUCTION_CONTAINER_NAME || true
-            docker rm $PREPRODUCTION_CONTAINER_NAME || true
+            docker stop $STAGING_CONTAINER_NAME || true
+            docker rm $STAGING_CONTAINER_NAME || true
             
             # Run the new container
             echo "Starting new container..."
@@ -299,10 +299,10 @@ jobs:
           name: Deploy to AWS production environment
           command: |
             set -x
-            ssh -o StrictHostKeyChecking=no $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST \<< 'EOF'
+            ssh -o StrictHostKeyChecking=no $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST \<< EOF
             
             # Docker login
-            docker login ghcr.io -u $GHCR_USERNAME --password $GHCR_PAT
+            echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
             
             # Pull the Docker image
             echo "Pulling image: $DOCKER_REPOSITORY:$CIRCLE_BRANCH"
@@ -509,7 +509,7 @@ workflows:
           name: build-docker-image-staging
           environment: staging
           <<: *dev_only
-          requires:
+          requires: # Best is to have fail safe metric jobs
             - metrics-phploc
             - metrics-phpmetrics
             - metrics-php-doc-check
